name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for node_modules
        run: chmod -R 755 node_modules

  backend-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for backend testing
        run: chmod +x ./node_modules/.bin/nyc

      - name: Run Backend Tests
        run: npm run backend-test

  frontend-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Fix permissions for Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress Frontend Tests
        run: npx cypress run --browser chrome
